// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3i2zOhcSyD0lA7DpGWtTkjJ09MIv2tM',
    appId: '1:204734453495:web:d41b285af20bc2fffe25f2',
    messagingSenderId: '204734453495',
    projectId: 'lojinhaclubeclother-c1a22',
    authDomain: 'lojinhaclubeclother-c1a22.firebaseapp.com',
    storageBucket: 'lojinhaclubeclother-c1a22.appspot.com',
    measurementId: 'G-6M0VV704T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzEjV8rs1qdXfnUwhdJTe8YjAg1HV6u3o',
    appId: '1:204734453495:android:2d40ec5d40a5eee0fe25f2',
    messagingSenderId: '204734453495',
    projectId: 'lojinhaclubeclother-c1a22',
    storageBucket: 'lojinhaclubeclother-c1a22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvJaMe5zAZmuNKxFMsAEAZwhDfAjvcQgA',
    appId: '1:204734453495:ios:5b82d6104b2c499efe25f2',
    messagingSenderId: '204734453495',
    projectId: 'lojinhaclubeclother-c1a22',
    storageBucket: 'lojinhaclubeclother-c1a22.appspot.com',
    iosClientId: '204734453495-q55vfcvba3cqtu8o9e0q0fo2s5dh9c98.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojinhaClubeclother',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvJaMe5zAZmuNKxFMsAEAZwhDfAjvcQgA',
    appId: '1:204734453495:ios:5b82d6104b2c499efe25f2',
    messagingSenderId: '204734453495',
    projectId: 'lojinhaclubeclother-c1a22',
    storageBucket: 'lojinhaclubeclother-c1a22.appspot.com',
    iosClientId: '204734453495-q55vfcvba3cqtu8o9e0q0fo2s5dh9c98.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojinhaClubeclother',
  );
}
